import = ["rocks-treesitter.toml"]
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
plugins_dir = "nvimrc/plugins/"
auto_setup = true

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"catppuccin.nvim" = { git = "catppuccin/nvim" }
"copilot.lua" = "scm"
"fidget.nvim" = "1.4.1"
"gitsigns.nvim" = "scm"
"indent-blankline.nvim" = "3.8.6"
"lspkind.nvim" = "scm"
"lspsaga.nvim" = { git = "nvimdev/lspsaga.nvim" }
"lualine.nvim" = "scm"
"neotree" = { git = "nvim-neo-tree/neo-tree.nvim" }
"none-ls.nvim" = "scm"
"nui.nvim" = "0.3.0"
"oil.nvim" = "2.14.0"
"rainbow-delimiters.nvim" = "0.8.0"
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.2"
"rocks-lazy.nvim" = "1.1.1"
"rocks-treesitter.nvim" = "1.3.0"
"rocks.nvim" = "2.43.0"
"schemastore.nvim" = "0.2.0"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.13.1"
"which-key.nvim" = "3.15.0"
cmp-buffer = "scm"
cmp-cmdline = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
nvim-cmp = "scm"
nvim-lspconfig = "1.3.0"
nvim-surround = "2.1.5"
rustaceanvim = "5.22.0"
tree-sitter-css = "0.0.31"
tree-sitter-gitignore = "0.0.29"
tree-sitter-html = "0.0.33"
tree-sitter-htmldjango = "0.0.29"
tree-sitter-java = "0.0.37"
tree-sitter-markdown = "0.0.37"
tree-sitter-markdown_inline = "0.0.37"
tree-sitter-robots = "0.0.29"
tree-sitter-rust = "0.0.38"
tree-sitter-toml = "0.0.31"
tree-sitter-yaml = "0.0.30"

# Plugin configurations

[plugins."dressing.nvim"]
version = "3.1.1"

[plugins."dressing.nvim".config]
input = { border = "none" }

[plugins."tiny-inline-diagnostic.nvim"]
git = "rachartier/tiny-inline-diagnostic.nvim"

[plugins."tiny-inline-diagnostic.nvim".config]
show_source = true

[plugins.neogit]
version = "scm"

[plugins.neogit.config]
disable_builtin_notifications = true
disable_commit_confirmation = true
disable_line_numbers = false
graph_style = "unicode"
commit_popup = { kind = "vsplit" }
preview_buffer = { kind = "vsplit" }
popup = { kind = "vsplit" }


[plugins."crates.nvim"]
git = "saecki/crates.nvim"
[plugins."crates.nvim".config]
null_ls = { enabled = true, name = "crates.nvim" }


[plugins.nvim-treesitter-context]
version = "scm"
config.multiline_threshold = 5

[treesitter]
auto_highlight = "all"
auto_install = "prompt"
disable = ["neo-tree"]

[treesitter.parser_map]
PKGBUILD = "bash"
