import = ["rocks-treesitter.toml"]
# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
plugins_dir = "nvimrc/plugins/"
auto_setup = false

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]

# Core rocks plugins
"rocks.nvim" = "2.46.1"
"rocks-config.nvim" = "3.1.2"
"rocks-git.nvim" = "2.5.6"
"rocks-lazy.nvim" = "1.2.2"
"rocks-treesitter.nvim" = "1.3.1"

"fidget.nvim" = { version = "1.6.0", event = "UIEnter" }
"gitsigns.nvim" = { version = "scm", config = true, event = "BufRead" }
"indent-blankline.nvim" = { version = "3.9.0", config = true, event = "BufEnter" }
"lualine.nvim" = { version = "scm", config = true, event = "UIEnter" }
"none-ls.nvim" = { version = "scm", event = "VimEnter" }
"nui.nvim" = "0.4.0"
"oil.nvim" = { version = "2.15.0", config = true, cmd = "Oil" }
"rainbow-delimiters.nvim" = { version = "0.9.1", config = true, event = "BufEnter" }
"schemastore.nvim" = { version = "0.2.0" }
"telescope.nvim" = { version = "scm", event = "UIEnter" }
"which-key.nvim" = { version = "3.17.0", config = true, event = "UIEnter" }
"lazydev.nvim" = { version = "1.9.0", config = true, ft = "lua" }

nvim-surround = { version = "3.1.6", config = true, event = "BufEnter" }
rustaceanvim = { version = "6.9.2" }
nvim-lspconfig = "2.5.0"

[plugins."catppuccin.nvim"]
git = "catppuccin/nvim"
rev = "v1.11.0"
branch = "main"

[plugins."toggleterm.nvim"]
version = "2.13.1"
keys = [
  { lhs = "<leader><cr>", rhs = "<Cmd>ToggleTerm<cr>", desc = "Toggle terminal" },
  { lhs = "<leader><A-cr>", rhs = "<Cmd>ToggleTerm direction=float<cr>", desc = "Toggle terminal" },
]

[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
rev = "30321e33b03cb924fdcd6a806a0dc6fa0b0eafb9"
branch = "master"

[plugins."copilot-lualine"]
git = "AndreM222/copilot-lualine"
rev = "dc4b8ed0f75bc2557b3158c526624bf04ad233ea"
branch = "main"

[plugins.neotree]
git = "nvim-neo-tree/neo-tree.nvim"
rev = "3.37.0"

[plugins."dressing.nvim"]
version = "3.1.1"
config = { input = { border = "none" } }
event = "UIEnter"

[plugins.neogit]
version = "scm"
cmd = "Neogit"

[plugins.neogit.config]
disable_builtin_notifications = true
disable_commit_confirmation = true
disable_line_numbers = false
graph_style = "unicode"
commit_popup = { kind = "vsplit" }
preview_buffer = { kind = "vsplit" }
popup = { kind = "vsplit" }

[plugins."crates.nvim"]
git = "saecki/crates.nvim"
rev = "v0.7.1"

[plugins.nvim-treesitter-context]
version = "scm"
event = "BufEnter"
config.multiline_threshold = 5

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v1.7.0"
branch = "main"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"
config_path = "rocks-treesitter.toml"
disable = ["neo-tree"]

[treesitter.parser_map]
PKGBUILD = "bash"
