[plugins]
tree-sitter-bash = "0.0.38"
tree-sitter-c = "0.0.37"
tree-sitter-cmake = "0.0.31"
tree-sitter-cpp = "0.0.36"
tree-sitter-css = "0.0.34"
tree-sitter-diff = "0.0.32"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-editorconfig = "0.0.47"
tree-sitter-fish = "0.0.30"
tree-sitter-git_config = "0.0.29"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-gitignore = "0.0.29"
tree-sitter-html = "0.0.34"
tree-sitter-htmldjango = "0.0.29"
tree-sitter-java = "0.0.38"
tree-sitter-json = "0.0.34"
tree-sitter-kotlin = "0.0.32"
tree-sitter-markdown = "0.0.37"
tree-sitter-markdown_inline = "0.0.37"
tree-sitter-nix = "0.0.54"
tree-sitter-perl = "0.0.37"
tree-sitter-python = "0.0.38"
tree-sitter-robots = "0.0.29"
tree-sitter-rust = "0.0.39"
tree-sitter-ssh_config = "0.0.32"
tree-sitter-swift = "0.0.44"
tree-sitter-tmux = "0.0.29"
tree-sitter-toml = "0.0.31"
tree-sitter-yaml = "0.0.31"
tree-sitter-zig = "0.0.34"
