import = ["rocks-treesitter.toml"]
# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
plugins_dir = "nvimrc/plugins/"
auto_setup = false

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]

# Core rocks plugins
"rocks.nvim" = "2.43.0"
"rocks-config.nvim" = "3.1.0"
"rocks-git.nvim" = "2.5.2"
"rocks-lazy.nvim" = "1.1.1"
"rocks-treesitter.nvim" = "1.3.0"

"fidget.nvim" = { version = "1.4.1" }
"gitsigns.nvim" = { version = "scm", config = true, event = "BufRead" }
"indent-blankline.nvim" = { version = "3.8.6", config = true, event = "BufEnter" }
"lspkind.nvim" = { version = "scm" }
"lualine.nvim" = { version = "scm", config = true, event = "UIEnter" }
"none-ls.nvim" = { version = "scm", config = true }
"nui.nvim" = "0.3.0"
"oil.nvim" = { version = "2.14.0", config = true, cmd = "Oil" }
"rainbow-delimiters.nvim" = { version = "0.8.0", config = true, event = "BufEnter" }
"schemastore.nvim" = { version = "0.2.0" }
"telescope.nvim" = { version = "scm" }
"which-key.nvim" = { version = "3.15.0", config = true, event = "UIEnter" }
"lazydev.nvim" = { version = "1.9.0", config = true, ft = "lua" }

# Auto completion
nvim-cmp = { version = "scm" }
cmp-buffer = "scm"
cmp-cmdline = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"

nvim-lspconfig = { version = "1.3.0" }
nvim-surround = { version = "2.1.5", config = true, event = "InsertEnter" }
rustaceanvim = { version = "5.22.0", config = true, ft = "rust" }

tree-sitter-css = "0.0.31"
tree-sitter-gitignore = "0.0.29"
tree-sitter-html = "0.0.33"
tree-sitter-htmldjango = "0.0.29"
tree-sitter-java = "0.0.37"
tree-sitter-markdown = "0.0.37"
tree-sitter-markdown_inline = "0.0.37"
tree-sitter-robots = "0.0.29"
tree-sitter-rust = "0.0.38"
tree-sitter-toml = "0.0.31"
tree-sitter-yaml = "0.0.30"
tree-sitter-json = "0.0.33"

# Color themes
[plugins."catppuccin.nvim"]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins."toggleterm.nvim"]
version = "2.13.1"
keys = [
  { lhs = "<leader><cr>", rhs = "<Cmd>ToggleTerm<cr>", desc = "Toggle terminal" },
  { lhs = "<leader><A-cr>", rhs = "<Cmd>ToggleTerm direction=float<cr>", desc = "Toggle terminal" },
]

# Copilot
[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
branch = "master"
event = "InsertEnter"

[plugins."copilot-lualine"]
git = "AndreM222/copilot-lualine"
branch = "main"

[plugins."lspsaga.nvim"]
git = "nvimdev/lspsaga.nvim"
branch = "main"

[plugins.neotree]
git = "nvim-neo-tree/neo-tree.nvim"
rev = "3.27"
cmd = "Neotree"
keys = [
  { lhs = "<leader>e", rhs = "<Cmd>Neotree toggle<cr>", desc = "Toggle file tree" },
]

[plugins."dressing.nvim"]
version = "3.1.1"
config = { input = { border = "none" } }

[plugins."tiny-inline-diagnostic.nvim"]
git = "rachartier/tiny-inline-diagnostic.nvim"
event = "LspAttach"
config = true

[plugins.neogit]
version = "scm"
cmd = "Neogit"

[plugins.neogit.config]
disable_builtin_notifications = true
disable_commit_confirmation = true
disable_line_numbers = false
graph_style = "unicode"
commit_popup = { kind = "vsplit" }
preview_buffer = { kind = "vsplit" }
popup = { kind = "vsplit" }

[plugins."crates.nvim"]
git = "saecki/crates.nvim"
rev = "v0.5.2"
event = "BufRead Cargo.toml"
config = true

[plugins.nvim-treesitter-context]
version = "scm"
event = "BufEnter"
config.multiline_threshold = 5

[bundles.cmp]
items = ["nvim-cmp", "cmp-buffer", "cmp-nvim-lsp", "cmp-path", "cmp-cmdline"]
config = "nvimrc.bundles.cmp"
event = "InsertEnter"

[treesitter]
auto_highlight = "all"
auto_install = "prompt"
disable = ["neo-tree"]

[treesitter.parser_map]
PKGBUILD = "bash"
