[plugins]
tree-sitter-bash = "0.0.40"
tree-sitter-bibtex = "0.0.31"
tree-sitter-c = "0.0.42"
tree-sitter-cmake = "0.0.36"
tree-sitter-cpp = "0.0.41"
tree-sitter-css = "0.0.37"
tree-sitter-diff = "0.0.32"
tree-sitter-dockerfile = "0.0.30"
tree-sitter-editorconfig = "0.0.48"
tree-sitter-fish = "0.0.30"
tree-sitter-git_config = "0.0.29"
tree-sitter-git_rebase = "0.0.29"
tree-sitter-gitcommit = "0.0.34"
tree-sitter-gitignore = "0.0.29"
tree-sitter-go = "0.0.39"
tree-sitter-gomod = "0.0.34"
tree-sitter-html = "0.0.36"
tree-sitter-htmldjango = "0.0.29"
tree-sitter-ini = "0.0.30"
tree-sitter-java = "0.0.42"
tree-sitter-json = "0.0.36"
tree-sitter-kotlin = "0.0.32"
tree-sitter-latex = "0.0.33"
tree-sitter-make = "0.0.30"
tree-sitter-markdown = "0.0.40"
tree-sitter-markdown_inline = "0.0.38"
tree-sitter-nix = "0.0.59"
tree-sitter-perl = "0.0.43"
tree-sitter-python = "0.0.45"
tree-sitter-robots = "0.0.29"
tree-sitter-ruby = "0.0.35"
tree-sitter-rust = "0.0.47"
tree-sitter-ssh_config = "0.0.32"
tree-sitter-starlark = "0.0.31"
tree-sitter-swift = "0.0.51"
tree-sitter-tmux = "0.0.29"
tree-sitter-toml = "0.0.31"
tree-sitter-typst = "0.0.37"
tree-sitter-yaml = "0.0.32"
tree-sitter-zig = "0.0.34"
tree-sitter-just = "0.0.37"
