return {
  File = { icon = "󰈙", hl = "Tag" },
  Namespace = { icon = "󰌗", hl = "Include" },
  Package = { icon = "󰏖", hl = "Label" },
  Class = { icon = "󰌗", hl = "Include" },
  Property = { icon = "󰆧", hl = "@property" },
  Enum = { icon = "󰒻", hl = "@number" },
  Function = { icon = "󰊕", hl = "Function" },
  String = { icon = "󰀬", hl = "String" },
  Number = { icon = "󰎠", hl = "Number" },
  Array = { icon = "󰅪", hl = "Type" },
  Object = { icon = "󰅩", hl = "Type" },
  Key = { icon = "󰌋", hl = "" },
  Struct = { icon = "󰌗", hl = "Type" },
  Operator = { icon = "󰆕", hl = "Operator" },
  TypeParameter = { icon = "󰊄", hl = "Type" },
  StaticMethod = { icon = "󰠄 ", hl = "Function" },
}
