--- @type TSConfig
local options = {
  ensure_installed = {
    "bash",
    "bibtex",
    "c",
    "cmake",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "editorconfig",
    "fish",
    "git_config",
    "git_rebase",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "html",
    "htmldjango",
    "ini",
    "java",
    "json",
    "jsonc",
    "just",
    "kotlin",
    "latex",
    "lua",
    "make",
    "markdown",
    "markdown_inline",
    "nix",
    "perl",
    "python",
    "robots",
    "ruby",
    "rust",
    "ssh_config",
    "starlark",
    "swift",
    "tmux",
    "toml",
    "typst",
    "vim",
    "vimdoc",
    "xml",
    "yaml",
    "zig",
  },
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
  },
}

--- @type LazyPluginSpec[]
return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "master",
    event = "BufEnter",
    build = ":TSUpdate",
    opts = options,
    config = function(self, opts) require("nvim-treesitter.configs").setup(opts) end,
  },
  {
    "nvim-treesitter/nvim-treesitter-context",
    event = "BufEnter",
  },
}
